该Jupyter Notebook用于展示如何使用ScriptTraderApp模块，在CLI命令行下进行交易指令的调用

In [1]:
from vnpy.app.script_trader import init_cli_trading
from vnpy.gateway.ctp import CtpGateway
from vnpy.trader.utility import load_json

In [3]:
# 连接到服务器
setting = load_json("connect_ctp.json")
engine = init_cli_trading([CtpGateway])
engine.connect_gateway(setting, "CTP")

2020-12-21 12:50:42.372528	交易服务器连接成功
2020-12-21 12:50:42.378698	行情服务器连接成功
2020-12-21 12:50:42.407690	行情服务器登录成功
2020-12-21 12:50:42.407690	交易服务器授权验证成功
2020-12-21 12:50:42.423528	交易服务器登录成功
2020-12-21 12:50:42.530105	结算信息确认成功
2020-12-21 12:50:42.767057	合约信息查询成功

In [4]:
# 查询所有合约
engine.get_all_contracts(use_df=True)

,gateway_name,symbol,exchange,name,product,size,pricetick,min_volume,stop_supported,net_position,history_data,option_strike,option_underlying,option_type,option_expiry,option_portfolio,option_index,vt_symbol
0,CTP,CF109,Exchange.CZCE,棉花109,Product.FUTURES,5,5.0,1,False,False,False,0,,None,None,,,CF109.CZCE
1,CTP,TA109,Exchange.CZCE,化纤109,Product.FUTURES,5,2.0,1,False,False,False,0,,None,None,,,TA109.CZCE
2,CTP,SR109,Exchange.CZCE,白砂糖109,Product.FUTURES,10,1.0,1,False,False,False,0,,None,None,,,SR109.CZCE
3,CTP,CY109,Exchange.CZCE,棉纱109,Product.FUTURES,5,5.0,1,False,False,False,0,,None,None,,,CY109.CZCE
4,CTP,FG109,Exchange.CZCE,玻璃109,Product.FUTURES,20,1.0,1,False,False,False,0,,None,None,,,FG109.CZCE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,CTP,sc2206,Exchange.INE,原油2206,Product.FUTURES,1000,0.1,1,False,False,False,0,,None,None,,,sc2206.INE
587,CTP,sc2203,Exchange.INE,原油2203,Product.FUTURES,1000,0.1,1,False,False,False,0,,None,None,,,sc2203.INE
588,CTP,IC2102,Exchange.CFFEX,IC2102,Product.FUTURES,200,0.2,1,False,False,False,0,,None,None,,,IC2102.CFFEX
589,CTP,IF2102,Exchange.CFFEX,IF2102,Product.FUTURES,300,0.2,1,False,False,False,0,,None,None,,,IF2102.CFFEX
590,CTP,IH2102,Exchange.CFFEX,IH2102,Product.FUTURES,300,0.2,1,False,False,False,0,,None,None,,,IH2102.CFFEX

In [4]:
# 查询资金
engine.get_all_accounts(use_df=True)

,accountid,available,balance,frozen,gateway_name,vt_accountid
0,1888000315,10011029372761,10011029372761,0,OES,OES.1888000315

In [5]:
# 查询持仓
engine.get_all_positions(use_df=True)

,direction,exchange,frozen,gateway_name,pnl,price,symbol,volume,vt_positionid,vt_symbol,yd_volume
0,Direction.NET,Exchange.SSE,0,OES,0,4.1881,600010,296900,600010.SSE.Direction.NET,600010.SSE,1000000
1,Direction.NET,Exchange.SSE,0,OES,0,32.0068,600036,2300,600036.SSE.Direction.NET,600036.SSE,0

In [6]:
# 查询活动委托
engine.get_all_active_orders(use_df=True)

In [7]:
# 订阅行情
engine.subscribe(["600036.SSE"])

In [9]:
# 查询行情
engine.get_tick("600036.SSE", use_df=True)

,ask_price_1,ask_price_2,ask_price_3,ask_price_4,ask_price_5,ask_volume_1,ask_volume_2,ask_volume_3,ask_volume_4,ask_volume_5,...,limit_down,limit_up,low_price,name,open_interest,open_price,pre_close,symbol,volume,vt_symbol
0,34.6,34.62,34.63,34.64,34.65,0,0,0,0,0,...,0,0,33.85,,0,34.57,0.0,600036,1900,600036.SSE

In [10]:
# 委托下单
vt_orderid = engine.buy("600036.SSE", 32, 1000)
print(vt_orderid)

OES.1000124

In [11]:
# 查询特定委托
engine.get_order(vt_orderid)

OrderData(gateway_name='OES', symbol='600036', exchange=<Exchange.SSE: 'SSE'>, orderid='1000124', type=<OrderType.LIMIT: '限价'>, direction=<Direction.NET: '净'>, offset=<Offset.OPEN: '开'>, price=32, volume=1000, traded=1000, status=<Status.ALLTRADED: '全部成交'>, time=datetime.datetime(2019, 4, 30, 17, 31, 56, 965000, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))))

In [12]:
# 委托撤单
engine.cancel_order(vt_orderid)